package cn.crap.utils;

/**
 * @author Ehsan
 * 所有字段必须以S开头
 */
public interface ISetting {
	String S_SECRETKEY = "SECRETKEY";
	String S_VERIFICATIONCODE = "VERIFICATIONCODE";
	String S_LOGIN_VERIFICATION_CODE = "LOGIN_VERIFICATION_CODE";
	String S_VISITCODE = "VISITCODE";
	String S_COMMENTCODE = "COMMENTCODE";
	String S_LUCENE_DIR = "LUCENE_DIR";
	String S_INDEX_PAGE = "INDEX_PAGE";
	String S_TITLE = "TITLE";
	String S_ANONYMOUS_COMMENT = "ANONYMOUS_COMMENT";
	String S_KEYWORDS = "KEYWORDS";
	String S_DESCRIPTION = "DESCRIPTION";
	String S_ICON = "ICON";
	String S_LOGO = "LOGO";
	String S_DOMAIN = "DOMAIN";
	String S_MAIN_COLOR = "MAIN_COLOR";
}
